config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'pictures/create'
  end
  namespace :admin do
    get 'collections/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "search", to: "search#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources "users"
  namespace :admin do
      get "/", to: "home#index"
      resources :collections
      resources :types
      get '/user/:id/update_admin', to: "users#update_admin", as: :user_admin
      resources :pictures
      resources :users
      resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :detail_bills, dependent: :destroy
  has_many :products, through: :detail_bills
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :types, dependent: :destroy
    has_many :products, through: :types, dependent: :destroy
    validates :name, uniqueness: {case_sensitive: false}, presence: true,  length: {maximum: 50}
end

app/models/color.rb
class Color < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "colors_products"
end

app/models/detail_bill.rb
class DetailBill < ApplicationRecord
  belongs_to :bill
  belongs_to :product
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_attached_file :image, styles: { small: "20x20>", medium: "300x300>", thumb: "100x100>" }, path: ":rails_root/public/images/:filename",
                            url: "/images/:filename"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :pictures , dependent: :destroy
    belongs_to :type
    has_and_belongs_to_many :sizes, join_table: "products_sizes"
    has_and_belongs_to_many :colors, join_table: "colors_products"
    has_many :detail_bills
    has_many :bills, through: :detail_bills
    accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: proc { |attributes| attributes['photo'].blank? }
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 50}
end

app/models/size.rb
class Size < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "products_sizes"
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :collection
  has_many :products, dependent: :destroy
  validates :name, presence: true,  length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bills, dependent: :destroy

    has_secure_password
    validates :name, presence: true, length: {maximum: 30}
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :age, presence: true, numericality:{ only_integer: true, less_than: 120}
    validates :phone, presence: true, numericality: true, length:{minimum: 9, maximum: 15}
    attr_accessor :remember_token

    # mã hóa băm của chuỗi
    def User.digest string
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
                                                    BCrypt::Password.create(string, cost: cost)
    end

    # trả v mã random
    def User.new_token
       SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute :remember_digest, User.digest(remember_token)
    end

# sso sánh với cookie
    def authenticated? remember_token
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute :remember_digest, nil
    end

    def u_phone
      "0#{self.phone}"
    end

end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::AdminController
  def index
      @collections = Collection.all
      @collection = Collection.new
  end

  def show
    @collection = Collection.find params[:id]
    @types = @collection.types
    respond_to do |format|
        if @types
            format.html{}
            format.js{}
            format.json { render json: @collection }
        else
            format.html
            format.json{ render json: @collection.errors}
        end
    end
  end

  def create
      @collection = Collection.new collection_params
      respond_to do |format|
        if @collection.save
            format.html{ redirect_to @collection }
            format.js{}
            format.json{render json: @collection}
        else
            format.html{
                @collections = Collection.all
                render :index
            }
            format.json{ render json: @collection.errors,  status: :unprocessable_entity }
        end
      end

  end

  def update
    @collection = Collection.find_by id: params[:collection][:id]
    respond_to do |format|
      if @collection.update_attributes collection_params
          format.html{}
          format.js{}
          format.json{ render @collection}
      else
          format.html
          format.json{ render json: @collection.errors}
      end
    end
  end

  def destroy
    @collection = Collection.find params[:id]
    @id = params[:id]
    respond_to do |format|
        if @collection.destroy
            format.html{ flash[:success] = "Xóa thành công"}
            format.js{}
            format.json {}
        else
            format.html
            format.json { render @collection.errors }
        end
    end
  end

  private
  def collection_params
      params.require(:collection).permit :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :check_logout, only: [:new, :create]
  def new
  end

  def create
      user = User.find_by name: params[:session][:name]
      if user && user.authenticate(params[:session][:password])
          log_in user
          remember user
          flash[:success] ="You are logged in"
          if check_admin?
              redirect_to admin_path
          else
              redirect_to root_path
          end
      else
          flash[:danger] = "Invalid username/password combination"
          render :new
      end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You are logged out"
    redirect_to login_path
  end

  private
  def check_logout
    unless !logged_in?
        log_out
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
          log_in @user
          redirect_to root_path
          flash[:success] = "Signup success"
      else
          flash[:success] = "Signup fails"
          render :new
      end
    end

    private
    def user_params
      params.require(:user).permit :name, :address, :phone, :password, :password_confirmation, :age
    end

end

app/helpers/admin/collections_helper.rb
module Admin::CollectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_allcollections
        Collection.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
      session[:user_id] = user.id
    end

    def log_out
        forgot
        session.delete :user_id
        @current_user = nil
    end

    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find_by id: user_id
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by id: user_id
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
      current_user.present?
    end

    def check_admin?
      current_user.admin
    end

    def forgot
      current_user.forget
    end

    def remember user
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      #code
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/collections/_flash.html.erb
<%= flash.each do |key, msg| %>
<% end %>

app/views/admin/collections/_noti_collection.html.erb
<% if @collection.errors.any? %>
<div class="error-msg">
    <div class="error-users">
        <div class="error-count">
            <span>The form have <%= pluralize(@collection.errors.count, "errors") %></span>
        </div>
        <div class="errors_details">
            <ul>
                <% @collection.errors.full_messages.each do |m|%>
                <li><%= m %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>
<% end %>

app/views/admin/collections/_tr_collection.html.erb
<tr data-id="<%= collection.id %>" class="collection-<%= collection.id %>">
    <td class="name"><%= collection.name.upcase %></td>
    <td class="option">
        <%= link_to admin_collection_path(collection.id), class: "btn btn-primary", remote: true do %>
            <%= fa_icon "eye" %>
        <% end %>
        <%= link_to "#", class: "btn btn-success", data:{toggle: "modal", target: "#editCollections#{collection.id}", id: collection.id} do %>
            <%= fa_icon "edit" %>
        <% end %>
        <%= link_to "#", class: "btn btn-danger",data:{toggle: "modal", target: "#deleteCollections#{collection.id}", id: collection.id} do %>
            <%= fa_icon "trash" %>
        <% end %>
    </td>
</tr>

<!-- modal edit collection -->
<div class="modal fade editCollections-<%= collection.id %>" id="editCollections<%= collection.id %>" tabindex="-1" data-id="<%= collection.id %>" role="dialog" aria-labelledby="editUsersLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editUsersLabel">Chỉnh sửa thông tin Collection</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= form_with model: [:admin, collection] do |f| %>
                <%= f.hidden_field :id %>
                <div class="form-box">
                    <label class="sr-only" for="inlineFormInputGroupCollectionname">CollectionName</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                        </div>
                        <%= f.text_field :name, required: true, class: "form-control", id: "inlineFormInputGroupCollectionname", placeholder: "Collection name"   %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit "Save changes", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<!-- modal confirm delete User -->
<div class="modal fade deleteCollections-<%= collection.id %>" id="deleteCollections<%= collection.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Xóa <%= collection.name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Bạn có chắc muốn xóa <%= collection.name %> ?</p>
        </div>
        <div class="modal-footer">
          <%= link_to "Xoá", admin_collection_path(collection.id), class: "btn btn-danger delete", method: "DELETE", remote: true %>
          <button type="button" class="btn btn-secondary dis" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

app/views/admin/collections/_types_of_collection.html.erb
<div class="banner">
    <h4>Danh sách các loại giày dành cho <%= collection.name.upcase %></h4>
</div>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Thể loại</th>
    </tr>
  </thead>
  <tbody>
      <% count = 0 %>
      <% types.each do |t| %>
      <% count +=1 %>
        <tr>
          <th scope="row"><%= count %></th>
          <td><%= t.name %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/collections/create.js.erb
$('.list-collections').prepend('<%= j render "admin/collections/tr_collection", collection: @collection %>')
$('.name-add-collection').val('')
$('.collection-<%= @collection.id %>').css({'color': '#fff', 'background-color': '#28a745'})

app/views/admin/collections/destroy.js.erb
$(document).ready(function(){
    $('.deleteCollections-<%= @id %>').find('.modal-body').find('p').html("<%= j flash[:success] %>")
    $('.deleteCollections-<%= @id %>').find('.modal-footer').find('.delete').hide()
    $('.collection-<%= @id %>').css({'background-color':'#dc3545', 'color':'#dc3545'})
    $('.collection-<%= @id %>').find('.option').html('')
    $('.deleteCollections-<%= @id %>').find('.dis').removeClass('btn-secondary')
    $('.deleteCollections-<%= @id %>').find('.dis').addClass('btn-success')
    $('.deleteCollections-<%= @id %>').find('.dis').html('Xóa thành công')
})

app/views/admin/collections/index.html.erb
<%= provide :title, "quản lý Collections" %>
<%= content_for :stylesheets do %>
    <%= stylesheet_link_tag "admin/content", media: "all", "data-turbolinks-track" => true %>
<% end %>
<div class="wrapper">
    <div class="container">
        <div class="table-data">
            <div class="banner">
                <h3>Danh sách Collections</h3>
            </div>
            <div class="add-collection add">
                <%= form_with model: [:admin, @collection], class: "form-add", id: "form-add-collection" do |f|%>
                <div class="row">
                    <div class="col-md-2">
                        <span>Thêm Collection</span>
                    </div>
                    <div class="col-md-7">
                        <%= f.text_field :name, required: true, class: "form-control name-add-collection", placeholder: "collection name"   %>
                    </div>
                    <div class="col-md-3">
                        <%= f.button :submit, name:"comit", class: "btn btn-success button-comit" do %>
                        <%= fa_icon "plus" %>
                        <% end %>
                    </div>
                    <% end%>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 rolz">
                    <div class="ro-table">
                        <table id="table_collections" class="display text-center">
                            <thead>
                                <tr>
                                    <th>Collection</th>
                                    <th>Option</th>
                                </tr>
                            </thead>
                            <tbody class="list-collections">
                                <% @collections.each do |collection| %>
                                    <%= render "admin/collections/tr_collection", collection: collection %>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-6 rolz table-types">
                </div>
            </div>
        </div>
    </div>

</div>

<%= content_for :scripts do %>
<script type="text/javascript">
    $(document).ready( function () {
        $('#table_collections').DataTable({
            searching: true,
            ordering: true
        });
    } );

    $('#form-add-collection')
    .bind("ajax:success", function(data){
        console.log(data.detail)
    })
    .bind("ajax:error", function(data){
        console.log(data)
    })

    </script>
<% end %>

app/views/admin/collections/show.js.erb
$('.table-types').html('<%= j render "admin/collections/types_of_collection", types: @types, collection: @collection %>')

app/views/admin/collections/update.js.erb
$(".editCollections-<%= @collection.id %>").find('.close').click()
$(".collection-<%= @collection.id %>").remove()
$(".list-collections").prepend("<%= j render('admin/collections/tr_collection', collection: @collection) %>")
$(".collection-<%= @collection.id %>").css({'background-color': '#28a745', 'color': '#fff'})