config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'pictures/create'
  end
  namespace :admin do
    get 'collections/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "search", to: "search#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources "users"
  namespace :admin do
      get "/", to: "home#index"
      resources :collections
      resources :types
      get '/user/:id/update_admin', to: "users#update_admin", as: :user_admin
      resources :pictures
      resources :users
      resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :detail_bills, dependent: :destroy
  has_many :products, through: :detail_bills
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :types, dependent: :destroy
    has_many :products, through: :types, dependent: :destroy
    validates :name, uniqueness: {case_sensitive: false}, presence: true,  length: {maximum: 50}
end

app/models/color.rb
class Color < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "colors_products"
end

app/models/detail_bill.rb
class DetailBill < ApplicationRecord
  belongs_to :bill
  belongs_to :product
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_attached_file :image, styles: { small: "20x20>", medium: "300x300>", thumb: "100x100>" }, path: ":rails_root/public/images/:filename",
                            url: "/images/:filename"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :pictures , dependent: :destroy
    belongs_to :type
    has_and_belongs_to_many :sizes, join_table: "products_sizes"
    has_and_belongs_to_many :colors, join_table: "colors_products"
    has_many :detail_bills
    has_many :bills, through: :detail_bills
    accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: proc { |attributes| attributes['photo'].blank? }
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 50}
end

app/models/size.rb
class Size < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "products_sizes"
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :collection
  has_many :products, dependent: :destroy
  validates :name, presence: true,  length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bills, dependent: :destroy

    has_secure_password
    validates :name, presence: true, length: {maximum: 30}
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :age, presence: true, numericality:{ only_integer: true, less_than: 120}
    validates :phone, presence: true, numericality: true, length:{minimum: 9, maximum: 15}
    attr_accessor :remember_token

    # mã hóa băm của chuỗi
    def User.digest string
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
                                                    BCrypt::Password.create(string, cost: cost)
    end

    # trả v mã random
    def User.new_token
       SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute :remember_digest, User.digest(remember_token)
    end

# sso sánh với cookie
    def authenticated? remember_token
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute :remember_digest, nil
    end

    def u_phone
      "0#{self.phone}"
    end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def create
        @product = Product.new product_parmas
        if @product.save
            @pictures = Picture.where(id: params[:picture_id].split(','))
            @pictures.each do |p|
                p.update_attributes(product_id: @product.id)
            end
            flash[:success] = "Create successfully"
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def update
        byebug
      # @product = Product.find_by id: params[:product][:id]
      # respond_to do |format|
      #   if @product.update_attributes product_parmas
      #       flash[:success] = "Sửa thành công"
      #       format.html{}
      #       format.js{}
      #       format.json{ render @product}
      #   else
      #       format.html
      #       format.json{ render json: @product.errors}
      #   end
      # end
    end

    def destroy
      @product = Product.find params[:id]
      @id = params[:id]
      respond_to do |format|
          if @product.destroy
              flash[:success] = "Xoá thành công"
              format.html{ flash[:success] = "Xóa thành công"}
              format.js{}
              format.json {}
          else
              format.html
              format.json { render @product.errors }
          end
      end
    end

    private
    def product_parmas
      params.require(:product).permit :name, :amount, :price, :type_id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :check_logout, only: [:new, :create]
  def new
  end

  def create
      user = User.find_by name: params[:session][:name]
      if user && user.authenticate(params[:session][:password])
          log_in user
          remember user
          flash[:success] ="You are logged in"
          if check_admin?
              redirect_to admin_path
          else
              redirect_to root_path
          end
      else
          flash[:danger] = "Invalid username/password combination"
          render :new
      end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You are logged out"
    redirect_to login_path
  end

  private
  def check_logout
    unless !logged_in?
        log_out
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
          log_in @user
          redirect_to root_path
          flash[:success] = "Signup success"
      else
          flash[:success] = "Signup fails"
          render :new
      end
    end

    private
    def user_params
      params.require(:user).permit :name, :address, :phone, :password, :password_confirmation, :age
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_allcollections
        Collection.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
      session[:user_id] = user.id
    end

    def log_out
        forgot
        session.delete :user_id
        @current_user = nil
    end

    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find_by id: user_id
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by id: user_id
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
      current_user.present?
    end

    def check_admin?
      current_user.admin
    end

    def forgot
      current_user.forget
    end

    def remember user
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      #code
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_errors_product.html.erb
<% if @product.errors.any? %>
<div class="error-msg alert alert-danger">
    <div class="error-users">
        <div class="error-count">
            <span>Have <%= pluralize(@product.errors.count, "errors") %></span>
        </div>
        <div class="errors_details">
            <ul>
                <% @product.errors.full_messages.each do |m|%>
                <li><%= m %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>
<% end %>

app/views/admin/products/_tr_product.html.erb
<tr data-id="<%= product.id %>" class="product-<%= product.id %>">
    <td class="name"><%= product.name.capitalize %></td>
    <td class="amount"><%= product.amount %></td>
    <td class="price"><%= product.price %></td>
    <td class="type-of-product"><%= product.type.name %></td>
    <td class="collection-of-product"><%= product.type.collection.name %></td>
    <td class="option">
        <%= link_to "#", class: "btn btn-success", data:{toggle: "modal", target: "#editProducts#{product.id}", id: product.id} do %>
            <%= fa_icon "edit" %>
        <% end %>
        <%= link_to "#", class: "btn btn-danger",data:{toggle: "modal", target: "#deleteProducts#{product.id}", id: product.id} do %>
            <%= fa_icon "trash" %>
        <% end %>
    </td>
</tr>

<div class="modal fade editProducts-<%= product.id %>" id="editProducts<%= product.id %>" tabindex="-1" data-id="<%= product.id %>" role="dialog" aria-labelledby="editUsersLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editUsersLabel">Chỉnh sửa thông tin product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= form_with model: [:admin, product] do |f| %>
                <%= f.hidden_field :id %>
                <div class="form-box">
                    <label class="sr-only" for="inlineFormInputGroupproductname">productName</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                        </div>
                        <%= f.text_field :name, required: true, class: "form-control", id: "inlineFormInputGroupProductName", placeholder: "product name"   %>
                    </div>
                </div>
                <div class="form-box">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                        </div>
                        <%= f.number_field :amount, required: true, class: "form-control", id: "inlineFormInputGroupProductAmount", placeholder: "Số lượng"   %>
                    </div>
                </div>
                <div class="form-box">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                        </div>
                        <%= f.number_field :price, required: true, class: "form-control", id: "inlineFormInputGroupProductPrice", placeholder: "Số lượng"   %>
                    </div>
                </div>
                <div class="form-box">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                        </div>
                        <%= f.select :type_id, Type.all.collect{|t| [t.name, t.id]}, {include_blank:true}, {class: "custom-select", id:"type", required: true}%>
                    </div>
                </div>
                <% product.pictures.each do |pic|%>
                <div class="form-box form-edit-product">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <%= fa_icon "edit" %>
                            </div>
                            <div class="custom-file">
                                <div class="row">
                                    <div class="col-md-10">
                                        <%= f.file_field :picture, class: "custom-file-input form-control file-image-edit", id:"customFile#{pic.id}", name:"picture[image][]" %>
                                        <label class="custom-file-label" for="customFile<%= pic.id %>">Chose image</label>
                                    </div>
                                    <div class="col-md-2">
                                        <%= image_tag pic.image.url, class: "image-product" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit "Save changes", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<!-- modal confirm delete User -->
<div class="modal fade deleteProducts-<%= product.id %>" id="deleteProducts<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Xóa <%= product.name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Bạn có chắc muốn xóa <%= product.name %> ?</p>
        </div>
        <div class="modal-footer">
          <%= link_to "Xoá", admin_product_path(product.id), class: "btn btn-danger delete", method: "DELETE", remote: true %>
          <button type="button" class="btn btn-secondary dis" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

app/views/admin/products/destroy.js.erb
$(document).ready(function(){
    $('.deleteProducts-<%= @id %>').find('.modal-body').find('p').html("<%= j flash[:success] %>")
    $('.deleteProducts-<%= @id %>').find('.modal-footer').find('.delete').hide()
    $('.product-<%= @id %>').css({'background-color':'#dc3545', 'color':'#dc3545'})
    $('.product-<%= @id %>').find('.option').html('')
    $('.deleteProducts-<%= @id %>').find('.dis').removeClass('btn-secondary')
    $('.deleteProducts-<%= @id %>').find('.dis').addClass('btn-success')
    $('.deleteProducts-<%= @id %>').find('.dis').html('Xóa thành công')
})

app/views/admin/products/index.html.erb
<%= provide :title, "quản lý sản phẩm" %>
<%= content_for :stylesheets do %>
    <%= stylesheet_link_tag "admin/content", media: "all", "data-turbolinks-track" => true %>
<% end %>

<div class="wrapper">
    <div class="container">
        <div class="table-data">
            <div class="banner">
                <h3>Danh sách Sản Phẩm</h3>
            </div>
            <% flash.each do |type, msg| %>
            <div class="alert alert-<%= type %>">
                <%= msg %>
            </div>
            <% end %>
            <div class="row">
                <div class="col-md-12 rolz">
                    <div class="ro-table">
                        <table id="table_products" class="display text-center">
                            <thead>
                                <tr>
                                    <th>Tên sản phẩm</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá</th>
                                    <th>Thể loại</th>
                                    <th>Collection</th>
                                    <th>Option</th>
                                </tr>
                            </thead>
                            <tbody class="list-products">
                                <% @products.each do |product| %>
                                    <%= render "admin/products/tr_product", product: product %>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<%= content_for :scripts do %>
<script type="text/javascript">
    $(document).ready( function () {
        $('#table_products').DataTable({
            searching: true,
            ordering: true
        });
        // console.log($('.file-image-edit'))
        $('.file-image-edit').on('change', function(){
            var file = this.files[0];
            var reader = new FileReader();
            var image = $(this).closest('.custom-file').find('.image-product')
            if (file) {
                reader.readAsDataURL(file);
            }
            else {
                image.attr("src", "");
            }
            reader.onloadend = function () {
                image.attr("src", reader.result);
            }
        })
    } );
</script>
<% end %>

app/views/admin/products/new.html.erb
<%= provide :title, "Thêm sản phẩm" %>
<%= content_for :stylesheets do %>
    <%= stylesheet_link_tag "admin/content", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "dropzone", media: "all", "data-turbolinks-track" => true  %>
<% end %>

<div class="wrapper">
    <div class="container">
        <div class="table-data">
            <div class="banner pb-5">
                <h3>Thêm sản phẩm</h3>
            </div>
                <%= render "admin/products/errors_product" %>
            <div class="row">
                <div class="col-md-12 rolz">
                    <%= form_with model: [:admin, @product], local: true do |f| %>
                    <div class="form-group">
                        <label for="inputName">Tên sản phẩm</label>
                        <%= f.text_field :name, class: "form-control", id: "inputName" %>
                    </div>
                    <div class="form-group">
                        <label for="inputAmont">Số lượng</label>
                        <%= f.number_field :amount, class: "form-control", id: "inputAmount" %>
                    </div>
                    <div class="form-group">
                        <label for="inputPrice">Giá</label>
                        <%= f.number_field :price, class: "form-control", id: "inputPrice" %>
                    </div>
                    <div class="form-group">
                        <label for="type">Thể loại</label>
                        <%= f.select :type_id, Type.all.collect{|t| [t.name, t.id]}, {include_blank:true}, {class: "custom-select", id:"type", required: true}%>
                    </div>
                    <%= hidden_field_tag :picture_id %>
                    <div class="dropzone" id="mydropZone">
                    </div>
                    <div class="form-group text-center pt-4">
                        <%= button_tag "Tạo", name:"comit", class: "btn btn-primary" %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<%= content_for :scripts do %>
    <%= javascript_include_tag "dropzone", 'data-turbolinks-track': 'reload' %>
<script type="text/javascript">
Dropzone.autoDiscover = false;
$(document).ready(function(){
    var file_list = []
    var myDropzone = new Dropzone("div#mydropZone", {
        url: "<%= admin_pictures_path %>",
          paramName: "picture[image]",
          maxFiles: 3,
          addRemoveLinks: true,
          headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      },
        accept: function(file, done) {
            done();
        },
        init: function() {
            this.on("maxfilesexceeded", function(file){
                alert("Can't upload more file")
                this.files.pop();
                this.previewsContainer.removeChild(this.previewsContainer.lastChild);
            });
        },
        success: function(file, response){
			$(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
			$(file.previewElement).addClass("dz-success");
            file_list.push(response.fileID)
            $("input[name='picture_id']").val(file_list);
		},
        removedfile: function(file){
			var id = $(file.previewTemplate).find('.dz-remove').attr('id');
			$.ajax({
				type: 'DELETE',
				url: '/admin/pictures/'+ id,
                headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
				success: function(data){
					console.log(data.message);
				}
			});
            var i = file_list.indexOf(parseInt(id))
            if (i != -1) {
                file_list.splice(i, 1)
            }
            console.log(file_list)
            $("input[name='picture_id']").val(file_list);
            var _ref;
            return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
		},
    });
    // myDropzone.on("maxfilesexceeded", function(file){
    //     console.log('dqwdw')
    //     this.removedfile(file)
    // })

})
</script>
<% end %>

app/views/admin/products/update.js.erb
$(".editProducts-<%= @product.id %>").find('.close').click()
$(".product-<%= @product.id %>").remove()
$(".list-products").prepend("<%= j render('admin/products/tr_product', product: @product) %>")
$(".product-<%= @product.id %>").css({'background-color': '#28a745', 'color': '#fff'})