config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'pictures/create'
  end
  namespace :admin do
    get 'collections/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "search", to: "search#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources "users"
  namespace :admin do
      get "/", to: "home#index"
      resources :collections
      resources :types
      get '/user/:id/update_admin', to: "users#update_admin", as: :user_admin
      resources :pictures
      resources :users
      resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :detail_bills, dependent: :destroy
  has_many :products, through: :detail_bills
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :types, dependent: :destroy
    has_many :products, through: :types, dependent: :destroy
    validates :name, uniqueness: {case_sensitive: false}, presence: true,  length: {maximum: 50}
end

app/models/color.rb
class Color < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "colors_products"
end

app/models/detail_bill.rb
class DetailBill < ApplicationRecord
  belongs_to :bill
  belongs_to :product
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_attached_file :image, styles: { small: "20x20>", medium: "300x300>", thumb: "100x100>" }, path: ":rails_root/public/images/:filename",
                            url: "/images/:filename"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :pictures , dependent: :destroy
    belongs_to :type
    has_and_belongs_to_many :sizes, join_table: "products_sizes"
    has_and_belongs_to_many :colors, join_table: "colors_products"
    has_many :detail_bills
    has_many :bills, through: :detail_bills
    accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: proc { |attributes| attributes['photo'].blank? }
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 50}
end

app/models/size.rb
class Size < ApplicationRecord
    has_and_belongs_to_many :products, join_table: "products_sizes"
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :collection
  has_many :products, dependent: :destroy
  validates :name, presence: true,  length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bills, dependent: :destroy

    has_secure_password
    validates :name, presence: true, length: {maximum: 30}
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :age, presence: true, numericality:{ only_integer: true, less_than: 120}
    validates :phone, presence: true, numericality: true, length:{minimum: 9, maximum: 15}
    attr_accessor :remember_token

    # mã hóa băm của chuỗi
    def User.digest string
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
                                                    BCrypt::Password.create(string, cost: cost)
    end

    # trả v mã random
    def User.new_token
       SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute :remember_digest, User.digest(remember_token)
    end

# sso sánh với cookie
    def authenticated? remember_token
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute :remember_digest, nil
    end

    def u_phone
      "0#{self.phone}"
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
          log_in @user
          redirect_to root_path
          flash[:success] = "Signup success"
      else
          flash[:success] = "Signup fails"
          render :new
      end
    end

    private
    def user_params
      params.require(:user).permit :name, :address, :phone, :password, :password_confirmation, :age
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_allcollections
        Collection.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
      session[:user_id] = user.id
    end

    def log_out
        forgot
        session.delete :user_id
        @current_user = nil
    end

    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find_by id: user_id
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by id: user_id
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
      current_user.present?
    end

    def check_admin?
      current_user.admin
    end

    def forgot
      current_user.forget
    end

    def remember user
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      #code
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/_footer.html.erb
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>version</b>2.4.18
    </div>
    <strong>
        Copyright © 2014-2019
        <a href="">AdminLTE.</a>
    </strong>
    All rights reserved
</footer>

app/views/admin/layouts/_header.html.erb
<header class="main-header">
    <%= link_to admin_path, class: "logo" do %>
        <span class="logo-lg">
            <b>Admin</b>LTE
        </span>
    <% end %>

    <nav class="navbarez navbar-static-top">
        <a href="#" class="sidebar-toogle" data-toggle="push-menu">
            <%= fa_icon "align-justify" %>
        </a>
        <div class="navbar-custom-menu">
            <ul class="navbar-nav">
                <li class="dropdown messages-menu">
                    <a href="#" class="data-toggle" id="dropdownMenuLink-messages"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= fa_icon "envelope-o" %>
                        <span class="label-z bg-success">4</span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink-messages">
                        <li class="header">
                            You have 4 messages
                        </li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="">
                                        <div class="pull-left">
                                            <%= image_tag "user.jpg", class: "img-circle" %>
                                        </div>
                                        <div class="its-right">
                                            <h4>Support Team
                                                <small>
                                                    <%= fa_icon "clock-o", text: "5 mins" %>
                                                </small>
                                            </h4>
                                            <p>Why not buy a new awsome theme?</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <div class="pull-left">
                                            <%= image_tag "user2.jpg", class: "img-circle" %>
                                        </div>
                                        <div class="its-right">
                                            <h4>Support Team
                                                <small>
                                                    <%= fa_icon "clock-o", text: "7 mins" %>
                                                </small>
                                            </h4>
                                            <p>Why not buy a new awsome theme?</p>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <%= link_to "See all Messages" %>
                        </li>
                    </ul>
                </li>
                <li class="dropdown notifications-menu">
                    <a href="#" class="data-toggle" id="dropdownMenuLink-notifications"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= fa_icon "bell-o" %>
                        <span class="label-z bg-warning">10</span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink-notifications">
                        <li class="header">
                            You have 10 notifications
                        </li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <%= fa_icon "users", class: "text-aqua",
                                        text: "5 new members joined today"  %>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <%= fa_icon "warning", class: "text-yellow",
                                        text: " Very long description here that may not fit into the
                                          page and may cause design problems" %>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <%= fa_icon "users", class: "text-red",
                                        text: "5 new members joined"  %>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <%= fa_icon "shopping-cart", class: "text-green",
                                        text: "25 sales made"  %>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <%= fa_icon "user", class: "text-red",
                                        text: "you changed your name"  %>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <%= link_to "View all" %>
                        </li>
                    </ul>
                </li>
                <li class="dropdown tasks-menu">
                    <a href="#" class="data-toggle" id="dropdownMenuLink-tasks"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= fa_icon "flag-o" %>
                        <span class="label-z bg-danger">3</span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink-tasks">
                        <li class="header">
                            You have 9 tasks
                        </li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="">
                                        <h3>Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-aqua" role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <h3>Design some buttons
                                            <small class="pull-right">35%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-green" role="progressbar" style="width: 35%;" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <h3>Design some buttons
                                            <small class="pull-right">70%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-red" role="progressbar" style="width: 70%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <h3>Design some buttons
                                            <small class="pull-right">10%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-yellow" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <%= link_to "View all tasks" %>
                        </li>
                    </ul>
                </li>
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toogle" data-toggle="dropdown" id="dropdownUserMenu">
                        <%= image_tag "user", class: "user-image" %>
                        <span class="hidden-xs" class="name-acc"><%= current_user.name %></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownUserMenu">
                        <!-- User image -->
                        <li class="user-header">
                            <%= image_tag "user.jpg", class: "img-circle"%>
                            <p> <%= current_user.name %>
                            </p>
                        </li>
                        <!-- User body -->
                        <!-- <li class="user-body">
                            <div class="row">
                                <div class="col-4 text-center">
                                    <a href="">Flowers</a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="">Sales</a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="">Friends</a>
                                </div>
                            </div>
                        </li> -->
                        <!-- User footer -->
                        <li class="user-footer">
                            <div class="pull-left">
                                <%= link_to "Page", root_path ,class:"btn btn-default btn-flat" %>
                            </div>
                            <div class="pull-right">
                                <%= link_to "Sign out", logout_path, method: :delete, class: "btn btn-default btn-flat" %>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="" data-toggle="control-sidebar">
                        <%= fa_icon "gears" %>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/admin/layouts/_sidebar.html.erb
<aside class="main-sidebar">
    <section class="sidebar" style="height: auto;">
        <div class="user-panel">
            <div class="pull-left image">
                <%= image_tag "user.jpg", class: "img-circle" %>
            </div>
            <div class="pull-left info">
                <p><%= current_user.name %></p>
                <a href="">
                    <%= fa_icon "circle", text: "Online", class: "text-success" %>
                </a>
            </div>
        </div>
        <%= form_with url: "/search", class:"sidebar-form" do %>
        <div class="input-group">
            <%= text_field :person, :name, class: "form-control", placeholder: "Search" %>
            <span class="input-group-btn">
                <%= button_tag name: "search", class: "btn btn-flat", id: "search-btn" do %>
                    <%= fa_icon "search" %>
                <% end %>
            </span>
        </div>
        <% end %>
        <!-- sidebar menu -->
        <ul class="sidebar-menu tree" data-wiget="tree">
            <li class="header">MAIN NAVICATION</li>
            <li class="active treeview">
                <a href="#">
                    <%= fa_icon "dashboard" %>
                    <span>Dashboard</span>
                    <span class="pull-right-container">
                        <%= fa_icon "angle-left", class: "pull-right" %>
                    </span>
                </a>
                <ul class="treeview-menu" style="display:none;">
                    <li class="active">
                        <%= link_to admin_path do %>
                            <%= fa_icon "circle-o" %>
                            Dashboard v1
                        <% end %>
                    </li>
                    <li>
                        <a href="">
                            <%= fa_icon "circle-o" %>
                            Dashboard v2
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview">
                <%= link_to admin_collections_path do %>
                    <%= fa_icon "share" %>
                    <span>Collection</span>
                <% end %>
            </li>
            <li class="treeview">
                <%= link_to admin_types_path do %>
                    <%= fa_icon "share" %>
                    <span>Type</span>
                <% end %>
            </li>
            <li class="treeview">
                <%= link_to admin_users_path do %>
                    <%= fa_icon "share" %>
                    <span>Users</span>
                <% end %>
            </li>
            <li class="treeview">
                <a href="#">
                    <%= fa_icon "share" %>
                    <span>Products</span>
                    <span class="pull-right-container">
                        <%= fa_icon "angle-left", class: "pull-right" %>
                    </span>
                </a>
                <ul class="treeview-menu" style="display:none;">
                    <li class="">
                        <%= link_to admin_products_path do %>
                            <%= fa_icon "circle-o" %>
                            Danh sách sản phẩm
                        <% end %>
                    </li>
                    <li>
                        <%= link_to new_admin_product_path do %>
                            <%= fa_icon "circle-o" %>
                            Thêm sản phẩm
                        <% end %>
                    </li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trang <%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :stylesheets %>
  </head>

  <body style="height: auto">
      <div class="wrapper" style="min-height: 100%">
          <%= render 'admin/layouts/header' %>
          <%= render 'admin/layouts/sidebar' %>
          <div class="content-wrapper" style="min-height: 926px;">
              <%= yield %>
          </div>
          <%= render 'admin/layouts/footer' %>
      </div>
      <%= javascript_include_tag 'admin/admin', 'data-turbolinks-track': 'reload' %>
      <%= yield :scripts %>
  </body>
</html>

app/views/layouts/_carousel.html.erb
<div class="owl-carousel owl-theme carousel-head">
    <div class="item">
        <%= link_to "#" do %>
        <%= image_tag "owl1.jpg" %>
        <% end %>
    </div>
    <div class="item">
        <%= link_to "#" do %>
        <%= image_tag "owl2.webp" %>
        <% end %>
    </div>
    <div class="item">
        <%= link_to "#" do %>
        <%= image_tag "owl3.webp" %>
        <% end %>
    </div>
    <div class="item">
        <%= link_to "#" do %>
        <%= image_tag "owl4.webp" %>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6 atack-all">
                <div class="block-list">
                    <ul>
                        <li>
                            <%= link_to "Điều Khoản", "#"%>
                        </li>
                        <li>
                            <%= link_to "Chính Sách Bảo Mật" %>
                        </li>
                        <li>
                            <%= link_to "Hướng dẫn sử  dụng" %>
                        </li>
                    </ul>
                </div>
                <p class="hastag">
				    © Copyright Vitis.com.vn. Build by
                    <%= link_to "Lai Bá Vĩ", "#" %>
                </p>
            </div>
            <div class="col-md-2">
                <div class="bct">
                    <%= image_tag "dadangky" %>
                </div>
            </div>
            <div class="col-md-4">
                <p class="text-center license">
                    Giấy CNĐKDN: 0301340497 được cấp ngày 20/01/1992,
                    <br>
                    được sửa đổi lần thứ 20 ngày 28/12/2015 bởi Sở Kế hoạch và Đầu tư TPHCM
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <!-- header top && contact  -->
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="content-flex">
                        <div class="item-info-contact">
                            <a href="">
                                Hotline: 0966 158 666 (8h - 12h, 13h30-17h)
                            </a>
                        </div>
                        <div class="item-info-contact">
                            <a href="">
                                Tìm cửa hàng
                            </a>
                        </div>
                        <div class="item-info-contact">
                            <a href="">
                                Liên hệ hợp tác
                            </a>
                        </div>
                        <div class="item-info-contact">
                            <a href="">
                                ship hàng ra nước ngoài
                            </a>
                        </div>
                        <div class="item-info-contact">
                            <a href="">
                                Kiểm tra đơn hàng
                            </a>
                        </div>
                            <div class="link-login-signup">
                                <% if logged_in? %>
                                    <% if check_admin? %>
                                        <span>
                                            <%= link_to "Hi, #{current_user.name}", admin_path %>
                                        </span>|
                                    <% else %>
                                        <span>
                                            <%= link_to "Hi, #{current_user.name}", "#" %>
                                        </span>|
                                    <% end %>
                                    <span>
                                        <%= link_to "Đăng xuất", logout_path, method: "delete" %>
                                    </span>
                                <% else %>
                                    <span>
                                        <%= link_to "Đăng nhập", login_path %>
                                    </span>|
                                    <span>
                                        <%= link_to "Đăng kí", new_user_path%>
                                    </span>
                                <% end %>
                            </div>
                        <div class="item-info-contact">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header bottom list chose -->
    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="logo-wrap">
                        <%= link_to root_path do %>
                            <%= image_tag "logo-bitis", class: "image-logo" %>
                        <% end %>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="main-menu">
                        <% get_allcollections.each do |c| %>
                        <li class="item-menu">
                            <%= link_to c.name, "#" %>
                        </li>
                        <% end %>
                        <li class="item-menu">
                            <%= link_to "Về bitis", "#" %>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <%= form_with url: search_path, method: :get, class: "search_form" do |f| %>
                        <div class="search-form-wrap">
                            <%= f.text_field :search, class: "input-search", placeholder: "Nhập thông tin cần tìm kiếm..." %>
                            <%= button_tag class: "button-search" do %>
                                <%= fa_icon "search" %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
                <div class="col-md-1">
                    <div class="cart-right">
                        <div class="favorite">
                            <a href="">
                                <%= fa_icon "heart-o" %>
                            </a>
                        </div>
                        <div class="cart-header">
                            <a href="">
                                <span class="cart-icon">
                                    <%= fa_icon "shopping-cart" %>
                                </span>
                                <span class="cart-count">0</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :stylesheets %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :script %>
  </head>

  <body class="i-index">
      <div class="layoutz">
          <%= render "layouts/header" %>
          <%= yield %>
          <%= render "layouts/footer" %>
      </div>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
<div class="error-msg">
    <div class="error-users">
        <div class="error-count">
            <span>The form have <%= pluralize(@user.errors.count, "errors") %></span>
        </div>
        <div class="errors_details">
            <ul>
                <% @user.errors.full_messages.each do |m|%>
                <li><%= m %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>
<% end %>